/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy */

#ifndef _Included_edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy
#define _Included_edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy_BUFFER_SIZE
#define edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy_BUFFER_SIZE 4096L
/*
 * Class:     edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy
 * Method:    Tbs_getReturnCode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy_Tbs_1getReturnCode
  (JNIEnv *, jobject);

/*
 * Class:     edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy
 * Method:    Tbsip_Context_Create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy_Tbsip_1Context_1Create
  (JNIEnv *, jobject);

/*
 * Class:     edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy
 * Method:    Tbsip_Context_Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy_Tbsip_1Context_1Close
  (JNIEnv *, jobject);

/*
 * Class:     edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy
 * Method:    Tbsip_Cancel_Commands
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy_Tbsip_1Cancel_1Commands
  (JNIEnv *, jobject);

/*
 * Class:     edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy
 * Method:    Tbsip_Physical_Presence_Command
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy_Tbsip_1Physical_1Presence_1Command
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy
 * Method:    Tbsip_Submit_Command
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_mit_csail_tpmj_drivers_win32_WindowsVistaTBSProxy_Tbsip_1Submit_1Command
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
