/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_csail_tpmj_drivers_win32_Win32IFXTPMDriver */

#ifndef _Included_edu_mit_csail_tpmj_drivers_win32_Win32IFXTPMDriver
#define _Included_edu_mit_csail_tpmj_drivers_win32_Win32IFXTPMDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_csail_tpmj_drivers_win32_Win32IFXTPMDriver
 * Method:    _TDDL_Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_mit_csail_tpmj_drivers_win32_Win32IFXTPMDriver__1TDDL_1Open
  (JNIEnv *, jclass);

/*
 * Class:     edu_mit_csail_tpmj_drivers_win32_Win32IFXTPMDriver
 * Method:    _TDDL_Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_mit_csail_tpmj_drivers_win32_Win32IFXTPMDriver__1TDDL_1Close
  (JNIEnv *, jclass);

/*
 * Class:     edu_mit_csail_tpmj_drivers_win32_Win32IFXTPMDriver
 * Method:    _TDDL_TransmitData
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_csail_tpmj_drivers_win32_Win32IFXTPMDriver__1TDDL_1TransmitData
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
